### ISSUE TITLE
git@github.com: Permission denied (publickey). | While installing via documentation installation instructions

### ISSUE THREAD

**Issue by vexersa** [towfiqi/serpbear#162] opened 2024-02-12 07:45 UTC
When following the install guide her: https://docs.serpbear.com/deployment/running-serpbear-locally

And running Step 2: 
![image](https://github.com/towfiqi/serpbear/assets/7994227/07eb61ab-5e9b-43cf-b0bb-7060e7d6f8ce)

The following is returned: 
```
andrew@andrewpc:~/dev/serpbear$ git clone git@github.com:towfiqi/serpbear.git
Cloning into 'serpbear'...
The authenticity of host 'github.com (20.87.245.0)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by towfiqi** [comment] 2024-02-15 02:50
This is not caused by serpbear. so closing the issue.

**Closed by towfiqi** 2024-02-15 02:50 UTC
